<a href="https://colab.research.google.com/github/AbhilashJoshi25/Data_Science_And_ML/blob/main/Numpy_Series_GFG_ML_Course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.8/dist-packages/numpy/__init__.py'>

In [ ]:
lst = [[1, 2, 3], [1, 21, 3], [2, 5, 7]]

In [ ]:
type(lst)

list

In [ ]:
arr = np.array(lst)

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((8,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.random.random((5, 4))

array([[0.56397171, 0.16269863, 0.43001693, 0.23481962],
       [0.47127443, 0.94060989, 0.05830298, 0.44104792],
       [0.14499603, 0.2775339 , 0.69063396, 0.56207081],
       [0.8073254 , 0.58675054, 0.65053248, 0.48523321],
       [0.91450641, 0.18066911, 0.21001243, 0.69436908]])

In [ ]:
arr = np.random.random((5, 4))

In [ ]:
np.random.random()

0.7663854330752389

In [ ]:
x = np.random.random()
if x > 0.5:
  print("Number = {}".format (x))
else:
  print("Number less than 0.5")

Number = 0.7955441675071767


In [ ]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [ ]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.linspace(1, 7, 81)

array([1.   , 1.075, 1.15 , 1.225, 1.3  , 1.375, 1.45 , 1.525, 1.6  ,
       1.675, 1.75 , 1.825, 1.9  , 1.975, 2.05 , 2.125, 2.2  , 2.275,
       2.35 , 2.425, 2.5  , 2.575, 2.65 , 2.725, 2.8  , 2.875, 2.95 ,
       3.025, 3.1  , 3.175, 3.25 , 3.325, 3.4  , 3.475, 3.55 , 3.625,
       3.7  , 3.775, 3.85 , 3.925, 4.   , 4.075, 4.15 , 4.225, 4.3  ,
       4.375, 4.45 , 4.525, 4.6  , 4.675, 4.75 , 4.825, 4.9  , 4.975,
       5.05 , 5.125, 5.2  , 5.275, 5.35 , 5.425, 5.5  , 5.575, 5.65 ,
       5.725, 5.8  , 5.875, 5.95 , 6.025, 6.1  , 6.175, 6.25 , 6.325,
       6.4  , 6.475, 6.55 , 6.625, 6.7  , 6.775, 6.85 , 6.925, 7.   ])

In [ ]:
arr = np.random.random((4, 3))

In [ ]:
arr

array([[0.6754457 , 0.94758782, 0.69982705],
       [0.46058055, 0.60967914, 0.44184929],
       [0.62611667, 0.35244348, 0.70296806],
       [0.06931622, 0.46171626, 0.3934769 ]])

In [ ]:
arr = np.reshape(arr, (3, 4))

In [ ]:
arr

array([[0.6754457 , 0.94758782, 0.69982705, 0.46058055],
       [0.60967914, 0.44184929, 0.62611667, 0.35244348],
       [0.70296806, 0.06931622, 0.46171626, 0.3934769 ]])

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.ndim

2

In [ ]:
arr.flatten()

array([0.6754457 , 0.94758782, 0.69982705, 0.46058055, 0.60967914,
       0.44184929, 0.62611667, 0.35244348, 0.70296806, 0.06931622,
       0.46171626, 0.3934769 ])

In [ ]:
arr = np.array([1,2,3,4,5,6,7])

In [ ]:
arr + 1

array([2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr - 1

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr * 5

array([ 5, 10, 15, 20, 25, 30, 35])

In [ ]:
arr / 5

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4])

In [ ]:
print(arr + 1)
print(arr - 1)
print(arr * 5)
print(arr / 2)
print(arr % 2)
print(arr ** 4)

[2 3 4 5 6 7 8]
[0 1 2 3 4 5 6]
[ 5 10 15 20 25 30 35]
[0.5 1.  1.5 2.  2.5 3.  3.5]
[1 0 1 0 1 0 1]
[   1   16   81  256  625 1296 2401]


In [ ]:
from IPython.display import Image
try:
  filename = take_photo()
  print('Saved to {}'.format(filename))

  # Show the image which was just taken.
  display(Image(filename))
except Exception as err:
  # Errors will be thrown if the user does not have a webcam or if they do not
  # grant the page permission to access it.
  print(str(err))

name 'take_photo' is not defined


In [ ]:
arr =+ 1

In [ ]:
arr =  np.array([2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr += 1


In [ ]:
arr

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr *= 2

In [ ]:
arr

array([ 6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr.max()

18

In [ ]:
arr.min()

6

In [ ]:
arr = np.array([[1,2,3], [2,4,6],[8,1, 5]])

In [ ]:
arr

array([[1, 2, 3],
       [2, 4, 6],
       [8, 1, 5]])

In [ ]:
arr.max(axis = 0) #Maximum element column wise 0 represent column

array([8, 4, 6])

In [ ]:
arr.max(axis = 1) #Maximum element row wise 1 represent row

array([3, 6, 8])

In [ ]:
arr.min(axis = 1)

array([1, 2, 1])

In [ ]:
arr.min(axis = 0)

array([1, 1, 3])

In [ ]:
arr.sum() #Sum of all elements of the array

32

In [ ]:
9*9

81

In [ ]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6,],
                 [7, 8, 9]])

In [ ]:
arr2 = np.array([[9, 8, 7],
                 [6, 5, 4],
                 [3, 2, 1]])

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [ ]:
arr1.ndim

2

In [ ]:
arr1 + arr2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
arr2 * arr1

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [ ]:
arr3 = np.array([[4, 5, 6, 8],
         [2, 3, 4, 5],
         [7, 1, 2, 4]])

In [ ]:
arr3.ndim

2

In [ ]:
arr3.shape

(3, 4)

In [ ]:
arr3.size

12

In [ ]:
arr1.size

9

In [ ]:
arr3.shape

(3, 4)

In [ ]:
arr1+arr2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
arr2 * arr1

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [ ]:
arr1.dot(arr2) #dot product

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [ ]:
arr2.dot(arr1)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

In [ ]:
arr4 = arr1 @ arr2 # cross product

In [ ]:
arr4

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [ ]:
arr5 = arr2 @ arr1

In [ ]:
arr5

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

In [ ]:
arr = np.array([1,2,3,4,5])

In [ ]:
arr[:]

array([1, 2, 3, 4, 5])

In [ ]:
arr[:3]

array([1, 2, 3])

In [ ]:
arr[2:]

array([3, 4, 5])

In [ ]:
arr[:-2]

array([1, 2, 3])

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr1[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr1[:,1:2]

array([[2],
       [5],
       [8]])

In [ ]:
arr1[2:,:]

array([[7, 8, 9]])

In [ ]:
arr1[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
arr1[:,1:2]

array([[2],
       [5],
       [8]])

In [ ]:
arr1[1:2,:]

array([[4, 5, 6]])

In [ ]:
arr1[1:2,1:2]

array([[5]])

In [ ]:
arr1[1:, 1:]

array([[5, 6],
       [8, 9]])

Array Sorting

In [ ]:
import numpy as np

In [ ]:
y = np.array([[[7, 3, 8, 9, 6, 4],
              [1, 2, 3, 4, 5, 6],
              [9, 7, 5, 3, 4, 5],
              [4, 4, 4, 4, 4, 4]],
            [[3, 3, 3, 3, 3, 3,],
             [5, 5, 5, 5, 5, 5],
              [4, 4, 6, 6, 7, 7],
              [2, 2, 3, 3, 1, 1]],
            [[8, 5, 4, 3, 7, 9],
              [2, 4, 5, 3, 6, 7],
              [1, 0, 9, 6, 4, 3],
              [8, 9, 7, 0, 0, 0]]])

In [ ]:
y

array([[[7, 3, 8, 9, 6, 4],
        [1, 2, 3, 4, 5, 6],
        [9, 7, 5, 3, 4, 5],
        [4, 4, 4, 4, 4, 4]],

       [[3, 3, 3, 3, 3, 3],
        [5, 5, 5, 5, 5, 5],
        [4, 4, 6, 6, 7, 7],
        [2, 2, 3, 3, 1, 1]],

       [[8, 5, 4, 3, 7, 9],
        [2, 4, 5, 3, 6, 7],
        [1, 0, 9, 6, 4, 3],
        [8, 9, 7, 0, 0, 0]]])

In [ ]:
y.shape

(3, 4, 6)

In [ ]:
y.ndim

3

In [ ]:
np.sort(y, axis = 1, kind = 'mergesort')

array([[[1, 2, 3, 3, 4, 4],
        [4, 3, 4, 4, 4, 4],
        [7, 4, 5, 4, 5, 5],
        [9, 7, 8, 9, 6, 6]],

       [[2, 2, 3, 3, 1, 1],
        [3, 3, 3, 3, 3, 3],
        [4, 4, 5, 5, 5, 5],
        [5, 5, 6, 6, 7, 7]],

       [[1, 0, 4, 0, 0, 0],
        [2, 4, 5, 3, 4, 3],
        [8, 5, 7, 3, 6, 7],
        [8, 9, 9, 6, 7, 9]]])

In [ ]:
x = np.array([[7, 3, 8, 9, 6, 4],
              [1, 2, 3, 4, 5, 6],
              [9, 7, 5, 3, 4, 5],
              [4, 4, 4, 4, 4, 4]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(4, 6)

In [ ]:
np.sort(x, axis = 1, kind = 'quicksort') #sort requires matrix, axis (0 = column, 1 = row) and kind of sorting algorithm to be applied

array([[3, 4, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6],
       [3, 4, 5, 5, 7, 9],
       [4, 4, 4, 4, 4, 4]])

In [ ]:
np.sort(y, axis = 0, kind = 'heapsort')

array([[[3, 3, 3, 3, 3, 3],
        [1, 2, 3, 3, 5, 5],
        [1, 0, 5, 3, 4, 3],
        [2, 2, 3, 0, 0, 0]],

       [[7, 3, 4, 3, 6, 4],
        [2, 4, 5, 4, 5, 6],
        [4, 4, 6, 6, 4, 5],
        [4, 4, 4, 3, 1, 1]],

       [[8, 5, 8, 9, 7, 9],
        [5, 5, 5, 5, 6, 7],
        [9, 7, 9, 6, 7, 7],
        [8, 9, 7, 4, 4, 4]]])

In [ ]:
np.sort(y, axis = 0) # by default sorting is row wise

array([[[3, 3, 3, 3, 3, 3],
        [1, 2, 3, 3, 5, 5],
        [1, 0, 5, 3, 4, 3],
        [2, 2, 3, 0, 0, 0]],

       [[7, 3, 4, 3, 6, 4],
        [2, 4, 5, 4, 5, 6],
        [4, 4, 6, 6, 4, 5],
        [4, 4, 4, 3, 1, 1]],

       [[8, 5, 8, 9, 7, 9],
        [5, 5, 5, 5, 6, 7],
        [9, 7, 9, 6, 7, 7],
        [8, 9, 7, 4, 4, 4]]])

In [ ]:
y

array([[[7, 3, 8, 9, 6, 4],
        [1, 2, 3, 4, 5, 6],
        [9, 7, 5, 3, 4, 5],
        [4, 4, 4, 4, 4, 4]],

       [[3, 3, 3, 3, 3, 3],
        [5, 5, 5, 5, 5, 5],
        [4, 4, 6, 6, 7, 7],
        [2, 2, 3, 3, 1, 1]],

       [[8, 5, 4, 3, 7, 9],
        [2, 4, 5, 3, 6, 7],
        [1, 0, 9, 6, 4, 3],
        [8, 9, 7, 0, 0, 0]]])

In [ ]:
np.sort(y) #it choose best time complexity or random algorithm to sort and by default sort row wise

array([[[3, 4, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6],
        [3, 4, 5, 5, 7, 9],
        [4, 4, 4, 4, 4, 4]],

       [[3, 3, 3, 3, 3, 3],
        [5, 5, 5, 5, 5, 5],
        [4, 4, 6, 6, 7, 7],
        [1, 1, 2, 2, 3, 3]],

       [[3, 4, 5, 7, 8, 9],
        [2, 3, 4, 5, 6, 7],
        [0, 1, 3, 4, 6, 9],
        [0, 0, 0, 7, 8, 9]]])

Concatinating Arrays/Array Merging

In [ ]:
l = np.array(((1, 2, 3, 4, 5), (5, 6, 7, 8, 9)))
m = np.array(((9, 4, 3, 2, 1), (3, 5, 7, 8, 2)))

In [ ]:
l

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [ ]:
l.shape

(2, 5)

In [ ]:
l.size

10

In [ ]:
l.ndim

2

In [ ]:
m.shape

(2, 5)

In [ ]:
m.size

10

In [ ]:
m.ndim

2

In [ ]:
np.vstack((l, m))

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [9, 4, 3, 2, 1],
       [3, 5, 7, 8, 2]])

In [ ]:
np.hstack((l, m))

array([[1, 2, 3, 4, 5, 9, 4, 3, 2, 1],
       [5, 6, 7, 8, 9, 3, 5, 7, 8, 2]])

In [ ]:
n = np.concatenate((l, m))

In [ ]:
n

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [9, 4, 3, 2, 1],
       [3, 5, 7, 8, 2]])

In [ ]:
j = np.dstack((l, m))

In [ ]:
j

array([[[1, 9],
        [2, 4],
        [3, 3],
        [4, 2],
        [5, 1]],

       [[5, 3],
        [6, 5],
        [7, 7],
        [8, 8],
        [9, 2]]])

In [ ]:
j.shape

(2, 5, 2)

In [ ]:
j.ndim

3

In [ ]:
g = np.dsplit(j, np.array([2, 2]))

In [ ]:
g

[array([[[1, 9],
         [2, 4],
         [3, 3],
         [4, 2],
         [5, 1]],
 
        [[5, 3],
         [6, 5],
         [7, 7],
         [8, 8],
         [9, 2]]]),
 array([], shape=(2, 5, 0), dtype=int64),
 array([], shape=(2, 5, 0), dtype=int64)]

In [ ]:
g[0].shape

(2, 5, 2)

In [ ]:
g[0].ndim

3

In [ ]:
o = np.concatenate((m, l))

In [ ]:
o

array([[9, 4, 3, 2, 1],
       [3, 5, 7, 8, 2],
       [1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [ ]:
i = np.concatenate((l, m), axis=0)

In [ ]:
i

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [9, 4, 3, 2, 1],
       [3, 5, 7, 8, 2]])

In [ ]:
n

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [9, 4, 3, 2, 1],
       [3, 5, 7, 8, 2]])

In [ ]:
np.vsplit(n, 2)

[array([[1, 2, 3, 4, 5],
        [5, 6, 7, 8, 9]]),
 array([[9, 4, 3, 2, 1],
        [3, 5, 7, 8, 2]])]

In [ ]:
q = np.hsplit(n, np.array([2, 3]))

In [ ]:
q

[array([[1, 2],
        [5, 6],
        [9, 4],
        [3, 5]]),
 array([[3],
        [7],
        [3],
        [7]]),
 array([[4, 5],
        [8, 9],
        [2, 1],
        [8, 2]])]

In [ ]:
q[0]

array([[1, 2],
       [5, 6],
       [9, 4],
       [3, 5]])

In [ ]:
q[1]

array([[3],
       [7],
       [3],
       [7]])

In [ ]:
q[2]

array([[4, 5],
       [8, 9],
       [2, 1],
       [8, 2]])

In [ ]:
w = np.vsplit(n, np.array([3, 2]))

In [ ]:
n

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [9, 4, 3, 2, 1],
       [3, 5, 7, 8, 2]])

In [ ]:
w

[array([[1, 2, 3, 4, 5],
        [5, 6, 7, 8, 9],
        [9, 4, 3, 2, 1]]),
 array([], shape=(0, 5), dtype=int64),
 array([[9, 4, 3, 2, 1],
        [3, 5, 7, 8, 2]])]

In [ ]:
len(w)

3

Array Slicing - DAP
Indexing

In [ ]:
r = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 8, 7, 6], [2, 4, 5, 6]])

In [ ]:
r.shape

(4, 4)

In [ ]:
r

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6],
       [2, 4, 5, 6]])

In [ ]:
r.ndim

2

In [ ]:
r.size

16

In [ ]:
r[1]

array([5, 6, 7, 8])

In [ ]:
t = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
t

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
t[:] #left side of : and right side of : are boundary conditions

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
t[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [ ]:
t[:3]

array([1, 2, 3])

In [ ]:
t[:-3]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
t[3:-3]

array([4, 5, 6, 7])

In [ ]:
r [ : , : ] # left side of : on the left are the boundary conditions for rows
#right side of : on the right are are the boundary conditions for columns

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6],
       [2, 4, 5, 6]])

In [ ]:
r [ 1 : , 1 : 3 ] #remaining elements after the intersection point

array([[6, 7],
       [8, 7],
       [4, 5]])

In [ ]:
r [ : 1, : 1] # except the intersection point

array([[1]])

In [ ]:
r [2 , 1] #intersection point

8

In [ ]:
r [1:2 , 2:3]

array([[7]])

Automating with Numpy

In [ ]:
lst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
count = 0
for i in lst:
  if i > 5:
    count += 1
print(count)

5


In [ ]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
lst = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
lst > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
lst[lst > 5]

array([ 6,  7,  8,  9, 10])

In [ ]:
u = np.array(lst)

In [ ]:
u

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
u < 9 # gives a boolean value as T or F as per the condition

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False])

In [ ]:
u[ u < 9]  # passing this through the orignal array and
           #it gives the actual elements of the array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
len(u[u<9]) # len of the array

8

In [ ]:
print(len(u[u<9])) # prints the len of the numbers as per the condition
print(u[ u < 9]) # prints the number of elements as per the condition

8
[1 2 3 4 5 6 7 8]


In [ ]:
print(len(u[u % 3 == 0]))
print(u[ u % 3 == 0])

3
[3 6 9]


In [ ]:
c = np.array([6, 7, 5, 8])
d = np.array([4, 3, 7, 8])

In [ ]:
pro = c.dot(d)

In [ ]:
pro

144

In [ ]:
s = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [ ]:
s [ 1 : 2]

array([2])

In [ ]:
s [ 1 :: 2]

array([1, 3, 5, 7, 9])

In [ ]:
e = np.stack((c, d), axis=1)

In [ ]:
e

array([[6, 4],
       [7, 3],
       [5, 7],
       [8, 8]])

In [ ]:
l

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [ ]:
m

array([[9, 4, 3, 2, 1],
       [3, 5, 7, 8, 2]])

In [ ]:
np.stack((l, m), axis = 1)

array([[[1, 2, 3, 4, 5],
        [9, 4, 3, 2, 1]],

       [[5, 6, 7, 8, 9],
        [3, 5, 7, 8, 2]]])

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
b

array([[5, 6]])

In [ ]:
b.T

array([[5],
       [6]])

In [ ]:
np.concatenate((a, b.T), axis =1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
np.column_stack((l, m))

array([[1, 2, 3, 4, 5, 9, 4, 3, 2, 1],
       [5, 6, 7, 8, 9, 3, 5, 7, 8, 2]])